def FindTurtle(state):
    if state == "Alabama":
        return "Alabama Map Turtle, Box Turtle, Alabama Red-Bellied Cooter"
    elif state == "Alaska":
        return "Loggerhead Sea Turtle, Leatherback Sea Turtle, Green Sea Turtle"
    elif state == "Arizona":
        return "Snapping Turtle, Painted Turtle, Ornate Box Turtle, Pond Slider, Yellow Mud Turtle, Sonora Mud Turtle, Arizona Mud Turtle"
    elif state == "Arkansas":
        return "Snapping Turtle, Alligator Snapping Turtle, Southern Painted Turtle, Western Chicken Turtle, Northern Map Turtle, Ouachita Map Turtle, Mississippi Map Turtle, Eastern River Cooter, Three-toed Box Turtle, Ornate Box Turtle,Red-eared Slider, Mississippi Mud Turtle, Razor-backed Musk Turtle, Eastern Musk Turtle, Midland Smooth Softshell, Spiny Softshell, Yellow Mud Turtle, Western Painted Turtle"
    elif state == 'California ':
        return "Loggerhead Turtle, Olive Ridley Turtle, Leatherback Turtle"
    elif state == 'Colorado':
        return "Western Painted Turtle, Snapping Turtle, Yellow Mud Turtle, Spiny Softshell Turtle, Ornate Box Turtle"
    elif state == 'Connecticut':
        return "Atlantic Ridley Turtle or Kemps Ridley Turtle, Green Turtle, Leatherback Turtle, Loggerhead Turtle, Bog turtle, Box turtle, Diamondback terrapin, Musk turtle, Painted turtle, Snapping turtle, Spotted turtle, Wood turtle"
    elif state == "Delaware":
        return "Common Musk Turtle (Stinkpot) Sternotherus odoratus, Common Snapping Turtle Chelydra serpentina serpentina, Eastern Box Turtle Terrapene carolina carolina, Eastern Mud Turtle Kinosternon subrubrum subrubrum, Eastern Painted Turtle Chrysemys picta picta, Northern Diamondback Terrapin Malaclemys terrapin terrapin, Northern Redbelly Turtle Pseudemys rubriventris, Red-eared Slider Trachemys scripta elegans, Spotted Turtle Clemmys guttata"
    elif state == "Florida":
        return  "Florida Softshell, Gulf Coast Spiny Softshell, Loggerhead Sea Turtle, Green Sea Turtle, Florida Snapping Turtle, Common Snapping Turtle, Spotted Turtle, Florida Chicken Turtle, Eastern Chicken Turtle, Leatherback Sea Turtle, Gopher Tortoise, Barbours Map Turtle, Striped Mud Turtle, Eastern Mud Turtle, Alligator Snapping Turtle, Carolina Diamondback Terrapin, Ornate Diamondback Terrapin, Mangrove Diamondback Terrapin, Eastern Florida Diamondback Terrapin, River Cooter, River Cooter, Florida Redbelly Coote, Peninsula Cooter, Suwannee Cooter, Loggerhead Musk Turtle, Stripeneck Musk Turtle, Eastern Musk Turtle, Florida Box Turtle, Eastern Box Turtle, Gulf Coast Box Turtle, Three-toed Box Turtle, Red-eared Slider, Yellowbelly Slider"
    elif state == "Georgia":
        return "Common Snapping Turtle (Chelydra serpentina), Alligator Snapping Turtle (Macrochelys temminckii) Painted Turtle (Chrysemys picta) Spotted Turtle (Clemmys guttata)Chicken Turtle (Deirochelys reticularia)Bog Turtle (Glyptemys muhlenbergii)Barbours Map Turtle (Graptemys barbouri)Alabama Map Turtle (Graptemys pulchra)Common Map Turtle (Graptemys geographica)Diamondback Terrapin (Malaclemys terrapin)River Cooter (Pseudemys concinna)Florida Cooter (Pseudemys floridana)Florida Redbelly Turtle (Pseudemys nelsoni)Box Turtle (Terrapene carolina)Slider Turtle (Trachemys scripta)Striped Mud Turtle (Kinosternon baurii)Eastern Mud Turtle (Kinosternon subrubrum)Stripeneck/Loggerhead Musk Turtle (Sternotherus minor)Common Musk Turtle (Sternotherus odoratus)Florida Softshell (Apalone ferox)Spiny Softshell (Apalone spinifera)Loggerhead Sea Turtle (Caretta caretta)Green Sea Turtle (Chelonia mydas)Hawksbill Sea Turtle (Eretmochleys imbricata)Kemps Ridley Sea Turtle (Lepidochelys kempii)Family DermochelyidaeLeatherback Sea Turtle (Dermochelys coriacea)"
    elif state == "Hawaii":
        return "Hawaiian Green Sea Turtles, Hawksbill Sea Turtles, Leatherback Turtles"
    elif state == "Idaho":
        return "The Painted Turtle is the only species of turtle that occurs naturally in Idaho so identifying them should be straight forward.  However, due to escaped pets and introduced species, one must become familiar with the general characteristics of Painted Turtles to avoid confusing them with such turtles as Box Turtles, and Red-eared Sliders (both common pet species)."
    elif state == 'Illinois':
        return "Painted Turtle, Spotted Turtle, Blandings Turtle, Nothern Map Turtle, Ouachita Map Turtle, False Map Turtle, Eastern River Cooter, Eastern Box Turtle, Ornate Box Turtle, Pond Slider, Yellow Mud Turtle, Eastern Mud Turtle, Eastern Musk Turtle, Smooth Softshell, Spiny Softshell"
    elif state == "Indiana ":
        return "Spotted Turtles, Red-eared Sliders, Stinkpot Turtles. ...Eastern Mud Turtles. ...Map Turtles. ...Snapping Turtles. ...Softshell Turtles of Indiana. ...Box Turtles of Indiana."
    elif state == "Iowa":
        return "Snapping Turtle  (Chelydra serpentina) Painted Turtle  (Chrysemys picta) Blandings Turtle  (Emydoidea blandingii) Wood Turtle  (Clemmys insculpta) Northern Map Turtle (Graptemys geographica) Ouachita Map Turtle (Graptemys ouachitensis)False Map Turtle (Graptemys pseudogeographica)Ornate Box Turtle  (Terrapene ornata)Red-eared Slider (Trachemys scripta)Yellow Mud Turtle  (Kinosternon flavescens)Common Musk Turtle  (Sternotherus odoratus)Smooth Softshell Turtle  (Apalone mutica)Spiny Softshell Turtle (Apalone spinifera)"
    elif state == "Kansas":
        return "Alligator snapping turtleCommon snapping turtleCommon musk turtle (stinkpot)Yellow mud turtlePainted turtleCommon map turtleOuachita map turtleFalse map turtleRiver cooterornate box turtleeastern box turtlepond slider turtleSpiny softshellSmooth softshell"
    elif state == 'Kentucky':
        return "Smooth Softshell, Spiny Softshell, Common Snapping Turtle, Alligator Snapping Turtle, Eastern Mud Turtle, Common Musk Turtle, Southern/Midland Painted Turtle, Common Map Turtle, Ouachita Map Turtle, Mississippi Map Turtle, False Map Turtle, Eastern River Cooter, Red-eared Slider , Eastern Box Turtle"
    elif state == "Louisiana":
        return "Caretta caretta - Loggerhead Sea Turtle Chelonia mydas - Green Sea TurtleEretmochelys imbricata - Hawksbill Sea TurtleLepidochelys kempii - Kemps Ridley Sea TurtleFamily ChelydridaeChelydra serpentina - Snapping TurtleMacrochelys temminckii - Alligator Snapping TurtleFamily DermochelyidaeDermochelys coriacea - Leatherback Sea TurtleFamily KinosternidaeKinosternon subrubrum - Eastern Mud TurtleSternotherus carinatus - Razor-backed Musk TurtleSternotherus minor - Loggerhead Musk TurtleSternotherus odoratus - Eastern Musk TurtleFamily EmydidaeChrysemys dorsalis - Southern Painted TurtleDeirochelys reticularia - Chicken TurtleGraptemys oculifera - Ringed Map TurtleGraptemys ouachitensis - Ouachita Map TurtleGraptemys pearlensis - Pearl River Map TurtleGraptemys pseudogeographica - False Map TurtleGraptemys sabinensis - Sabine Map TurtleMalaclemys terrapin - Diamond-backed TerrapinPseudemys concinna - River CooterTerrapene carolina - Eastern Box TurtleTerrapene ornata - Ornate Box TurtleTrachemys scripta - Pond SliderFamily TestudinidaeGopherus polyphemus - Gopher TortoiseFamily TrionychidaeApalone ferox - Florida Softshell [Introduced]Apalone mutica - Smooth SoftshellApalone spinifera - Spiny Softshell"
    elif state == 'Maine':
        return "Eastern Painted, Midland Painted, Northern Snapping, Musk Turtles Spotted Turtle, Wood Turtle, Eastern Box Turtle, Blanding Turtle" 
    elif state == "Maryland":
        return "Eastern Musk Turtle, Eastern Mud Turtle, Eastern Box Turtle, Spotted Turtle, Bog Turtle, Wood Turtle Glyptemys insculptaNorthern Diamond-backed Terrapin Malaclemys terrapin terrapinNorthern Map Turtle Graptemys geographica EndangeredSMidland Painted Turtle Chrysemys picta marginataEastern Painted Turtle Chrysemys picta pictaRed-eared Slider Trachemys scripta elegans IntroducedNorthern Red-bellied Cooter Pseudemys rubriventrisEastern Snapping Turtle Chelydra serpentina serpentinaLoggerhead Sea Turtle Caretta caretta ThreatenedF,Kemps Ridley Sea Turtle Lepidochelys kempii EndangeredF,SGreen Sea Turtle Chelonia mydas ThreatenedF,SLeatherback Sea Turtle Dermochelys coriacea EndangeredF,SAtlantic Hawksbill Sea Turtle Eretmochelys imbricata imbricata EndangeredF,SEastern Spiny Softshell Apalone spinifera spinifera"
    elif state == 'Massachusetts':
        return "Turtle Species in Massachusetts. Blandings Turtle (Emydoidea blandingii) Bog Turtle (Glyptemys muhlenbergii) Diamond-backed Terrapin (Malaclemys terrapin) Eastern Box Turtle (Terrapene carolina) Northern Red-bellied Cooter (Pseudemys rubirentris) Wood turtle (Clemmys insculpta)"
    elif state == "Michigan":
        return "Blandings Turtle, Common Map Turtle, Common Musk Turtle, Eastern Box Turtle, Midland Painted Turtle, Red-eared Slider, Eastern Spiny Softshell, Spotted Turtle, Common Snapping Turtle, Wood Turtle"
    elif state == 'Minnesota':
        return "Blandings turtle, False map turtle, Northern map turtle, Ouachita map turtle, Painted turtle, Smooth softshell turtle, Snapping turtle, Spiny softshell turtle, Wood turtle"
    elif state == "Mississippi":
        return "Spiny Softshell Turtle, Painted Turt, Ouachita Map Turtle, Northern Map TurtleSpiny Softshell Turtle, Smooth Softshell Turtle , Green Sea Turtle, Loggerhead Sea Turtle, Hawksbill Sea Turtle, Leatherback Sea Turtle , Common Snapping Turtle, Common Musk Turtle , Loggerhead Musk Turtle , Razor-backed Musk Turtle , Eastern Mud Turtle , Chicken Turtle , Common Slider, Common Box Turtle, Alabama Red-bellied Turtle, Diamondback Terrapin, Alabama Map Turtle, False Map Turtle , Ringed Map Turtle, Pascagoula Map Turtle, Black-knobbed Map Turtle, Yellow-blotched Map Turtle, (Graptemys flavimaculata), Kemps Ridley Sea Turtle, Giant Goldenrod, Pearl River Map Turtle, Southern Painted Turtle, Turtle Barnacle , Ouachita Map Turtle, Mini Alligator Snapping Turtle , Alligator Snapping Turtle"
    elif state == "Missouri":
        return "Alligator Snapping Turtle Macroclemys temminckii, Blandings Turtle Emydoidea blandingii, Common Map Turtle Graptemys geographica, Common Musk Turtle (Stinkpot) Sternotherus odoratus, Common Snapping Turtle Chelydra serpentina serpentina, Eastern Spiny Softshell Apalone spinifera spinifera, False Map Turtle Graptemys pseudogeographica pseudogeographica, Illinois Mud Turtle Kinosternon flavescens spooneri, Midland Smooth Softshell Apalone mutica mutica, Mississippi Map Turtle Graptemys pseudogeographica kohnii, Mississippi Mud Turtle Kinosternon subrubrum hippocrepis, Missouri River Cooter Pseudemys concinna metteri, Ornate Box Turtle Terrapene ornata ornata, Ouachita Map Turtle Graptemys ouachitensis ouachitensis, Red-eared Slider Chrysemys scripta elegans ,Southern Painted Turtle Chrysemys picta dorsalis, Three-toed Box Turtle Terrapene carolina triunguis, Western Chicken Turtle Deirochelys reticularia miaria, Western Painted Turtle Chrysemys picta belli, Western Spiny Softshell Apalone spinifera hartwegi, Yellow Mud Turtle Kinosternon flavescens flavescens"
    elif state == "Montana":
        return"Common Snapping Turtle Chelydra serpentina serpentina, Western Painted Turtle Chrysemys picta bellii, Western Spiny Softshell Apalone spinifera hartwegi"
    elif state == "Nebraska":
        return "Blandings Turtle Emydoidea blandingii Common Snapping Turtle Chelydra serpentina serpentina, False Map Turtle Graptemys pseudogeographica pseudogeographica, Midland Smooth Softshell Apalone mutica mutica, Ornate Box Turtle Terrapene ornata ornata, Red-eared Slider Trachemys scripta elegans, Western Painted Turtle Chrysemys picta bellii, Western Spiny Softshell Apalone spinifera hartwegi, Yellow Mud Turtle Kinosternon flavescens flavescen"
    elif state == "Nevada":
        return "Desert Tortoise Gopherus agassizii, Northwestern Pond Turtle Emys marmorata marmorata, Spiny Softshell Apalone spinifera, Ornate Box Turtle Terrapene ornate, Painted Turtles Chrysemys picta, Arizona Mud Turtle Kinosternon arizonense, Yellow Mud Turtle Kinosternon flavescens ,Sonora Mud Turtle Kinosternon sonoriense"
    elif state == "New Hampshire":
        return "Blandings Turtle Emydoidea blandingii, Common Musk Turtle (Stinkpot) Sternotherus odoratus, Common Snapping Turtle Chelydra serpentina serpentina, Eastern Box Turtle Terrapene carolina carolina, Eastern Painted Turtle Chrysemys picta picta, Midland Painted Turtle Chrysemys picta marginata, Spotted Turtle Clemmys guttata, Wood Turtle Glyptemys insculpta"
    elif state == "New Jersey":
        return "Bog Turtle Glyptemys muhlenbergii, Common Map Turtle Graptemys geographica, Common Musk Turtle(Stinkpot) Sternotherus odoratus, Common Snapping Turtle Chelydra serpentina serpentina,Eastern Box Turtle Terrapene carolina carolina, Eastern Mud Turtle Kinosternon subrubrum subrubrum, Eastern Painted Turtle Chrysemys picta picta,Eastern Spiny Softshell Apalone spinifera spinifera,Midland Painted Turtle Chrysemys picta marginata ,Northern Diamondback Terrapin Malaclemys terrapin terrapin, Northern Redbelly Turtle Pseudemys rubriventris, Red-eared Slider Trachemys scripta elegans, Spotted Turtle Clemmys guttata, Wood Turtle Glyptemys insculpta"
    elif state == "New Mexico":
        return "Big Bend Slider Trachemys gaigeae,Common Snapping Turtle Chelydra serpentina serpentina,Desert Box Turtle Terrapene ornata luteola,Desert Tortoise Gopherus agassizii,Midland Smooth Softshell Apalone mutica mutica,Ornate Box Turtle Terrapene ornata ornate,Red-eared Slider Trachemys scripta elegans,Rio Grande River Cooter Pseudemys gorzugi,Sonoran Mud Turtle Kinosternon sonoriense,Texas Spiny Softshell Apalone spinifera emoryi,Western Painted Turtle Chrysemys picta bellii,Western Spiny Softshell Apalone spinifera hartwegi,Yellow Mud Kinosternon flavescens flavescens"
    elif state == "New York":
        return "Blandings Turtle Emydoidea blandingii, Bog Turtle Glyptemys muhlenbergii, Common Map Turtle Graptemys geographica, Common Musk Turtle (Stinkpot) Sternotherus odoratus, Common Snapping Turtle Chelydra serpentina serpentina, Eastern Box Turtle Terrapene carolina carolina, Eastern Mud Turtle Kinosternon subrubrum subrubrum, Eastern Spiny Softshell Apalone spinifera spinifera, Midland Painted Turtle Chrysemys picta marginata, Northern Diamondback Terrapin Malaclemys terrapin terrapin, Eastern Painted Turtle Chrysemys picta picta, Spotted Turtle Clemmys guttata, Wood Turtle Glyptemys insculpta, Yellowbelly Slider Trachemys scripta scripta"
    elif state == "North Carolina":
        return "Bog Turtle Glyptemys muhlenbergii, Carolina Diamondback terrapin Malaclemys terrapin centrata, Common Musk Turtle (Stinkpot) Sternotherus odoratus, Common Snapping Turtle Chelydra serpentina serpentina, Eastern Box Turtle Terrapene carolina carolina, Eastern Chicken Turtle Deirochelys reticularia,Eastern Mud Turtle Kinosternon subrubrum subrubrum, Eastern Painted Turtle Chrysemys picta picta, Eastern River Cooter Pseudemys concinna concinna, Eastern Spiny Softshell Apalone spinifera spinifera, Florida Cooter Pseudemys floridana floridana, Gulf Coast Spiny Softshell Apalone spinifera aspera, Northern Diamondback terrapin Malaclemys terrapin terrapin, Northern Redbelly Turtle Pseudemys rubriventris, Spotted Turtle Clemmys guttata, Striped Mud Turtle Kinosternon baurii, Stripeneck Musk Turtle Sternotherus minor peltifer, Yellowbelly Slider Trachemys scripta scripta"
    elif state == "North Dakota":
        return "Common Snapping Turtle Chelydra serpentina serpentina, False Map Turtle Graptemys pseudogeographica pseudogeographica, Midland Smooth Softshell Apalone mutica mutica, Western Painted Turtle Chrysemys picta bellii"
    elif state == "Ohio":
        return "Blandings Turtle (Emydoidea blandingii), Common Map Turtle (Graptemys geographica), Common Musk Turtle (Stinkpot) (Sternotherus odoratus), Common Snapping Turtle (Chelydra serpentina serpentina), Eastern Box Turtle (Terrapene carolina carolina), Eastern Spiny Softshell (Apalone spinifera spinifera), Midland Painted Turtle (Chrysemys picta marginata), Midland Smooth Softshell (Apalone mutica mutica), Ouachita Map Turtle (Graptemys ouachitensis ouachitensis), Red-eared Slider (Trachemys scripta elegans), Spotted Turtle (Clemmys guttata), Wood Turtle (Glyptemys insculpta)"
 #**I found a great website:http://www.nauti-lasscritters.com/laws-by-state.html It lists the laws per state, as well as the turtles which live there.
    elif state =='Oklahoma':
        return "Alligator Snapping Turtle, Common Map Turtle, Common Musk Turtle (Stinkpot), Common Snapping Turtle, Midland Smooth Softshel, Mississippi Map Turtle, Mississippi Mud, Missouri River Cooter, Ornate Box, Ouachita Map Turtle, Pallid Spiny Softshell, Razorback Musk, Red-eared Slider, Southern Painted, Three-Toed Box, Western Chicken Turtle, Western Painted, Western Spiny Softshell, Yellow Mud"
    elif state == 'Oregon':
        return "Western Painted Turtle, Western Pond Turtle"
    elif state == 'Pennsylvania':
        return "Blandings Turtle, Bog Turtle, Common Map Turtle, Common Musk Turtle (Stinkpot), Common Snapping Turtle, Eastern Box Turtle, Eastern Painted Turtle, Eastern Spiny Softshell, Midland Painted Turtle, Midland Smooth Softshell, Northern Redbelly Turtle, Spotted Turtle, Wood Turtle"
    elif state == 'Rhode Island':
        return "Blandings Turtle, Common Musk Turtle (Stinkpot), Common Snapping Turtle, Eastern Box Turtle, Eastern Painted Turtle, Northern Diamondback terrapin, Spotted Turtle, Wood Turtle"
    elif state == 'South Carolina':
        return "Bog Turtle, Carolina Diamondback terrapin, Common Musk Turtle, Common Snapping Turtle, Eastern Box Turtle, Eastern Chicken Turtle, Eastern Mud Turtle, Eastern Painted Turtle, Eastern River Cooter, Florida Cooter, Florida Softshell Turtle, Gopher Tortoise, Gulf Coast Spiny Softshell Turtle, Striped Mud Turtle, Spotted Turtle, Yellowbelly Slider"
    elif state == 'South Dakota':
        return "Blandings Turtle, Common Snapping Turtle, False Map Turtle, Midland Smooth Softshell, Ornate Box Turtle, Western Painted, Western Spiny Softshell"
    elif state == "Tennessee":
        return "Alligator Snapping Turtle, Bog Turtle, Common Musk Turtle (Stinkpot), Common Map Turtle, Common Snapping Turtle, Cumberland Slider, Eastern Box Turtle, Eastern Mud Turtle, Eastern Painted Turtle, Eastern River Cooter, Eastern Spiny Softshel, Hieroglyphic River Cooter, Midland Painted Turtle, Midland Smooth Softshell, Mississippi Map Turtle, Ouachita Map Turtle, Red-eared Slider, Southern Painted Turtle, Stripeneck Musk Turtle, Three-toed Box Turtle"
    elif state == 'Texas':
        return "Alligator Snapping Turtle, Big Bend Mud Turtle, Big Bend Mud Turtle, Big Bend Slider, Cagles Map Turtle, Common Musk Turtle (Stinkpot), Common Snapping Turtle, Desert Box Turtle, Guadalupe Spiny Softshell, Midland Smooth Softshell, Mississippi Map Turtle, Mississippi Mud Turtle, Missouri River Cooter, Ornate Box Turtle, Ouachita Map Turtle, Pallid Spiny Softshell, Razorback Musk Turtle, Red-eared Slider, Rio Grande River Cooter, Sabine Map Turtle, Southern Painted Turtle, Texas Diamondback Terrapin, Texas Map Turtle, Texas River Cooter, Texas Spiny Softshell, Texas Tortoise, Three-toed Box Turtle, Western Chicken Turtle, Western Painted Turtle, Western Spiny Softshell, Yellow Mud Turtle"
    elif state == "Utah":
        return "Common Snapping Turtle, Desert Tortoise, Texas Spiny Softshell, Western Painted Turtle"
    elif state == 'Vermont':
        return "Common Map Turtle, Common Musk Turtle (Stinkpot), Common Snapping Turtle, Eastern Painted Turtle, Eastern Spiny Softshell, Midland Painted Turtle, Spotted Turtle, Wood Turtle"
    elif state == "Virginia":
        return "Bog Turtle, Common Map Turtle, Common Musk Turtle (Stinkpot), Common Snapping Turtle, Cumberland Slider, Eastern Box Turtle, Eastern Chicken Turtle, Eastern Mud Turtle, Eastern Painted Turtle, Eastern River Cooter, Eastern Spiny Softshell, Florida Cooter, Midland Painted Turtle, Northern Diamondback Terrapin, Northern Redbelly Turtle, Red-eared Slider, Spotted Turtle, Striped Mud Turtle, Stripeneck Musk Turtle, Wood Turtle, Yellowbelly Slider"
    elif state == 'Washington':
        return "Common Snapping Turtle, Northern Pacific Pond Turtle, Northern Pacific Pond Turtle, Western pond turtle"
    elif state == "West Virginia":
        return "Common Map Turtle (Graptemys geographica), Common Musk Turtle (Stinkpot) (Sternotherus odoratus), Common Snapping Turtle (Chelydra serpentina serpentina), Eastern Box Turtle (Terrapene carolina carolina), Eastern Painted Turtle (Chrysemys picta picta), Eastern River Cooter (Pseudemys concinna concinna),  Eastern Spiny Softshell (Apalone spinifera spinifera), Midland Painted Turtle (Chrysemys picta marginata), Midland Smooth Softshell (Apalone mutica mutica), Northern Redbelly Turtle (Pseudemys rubriventris), Ouachita Map Turtle (Graptemys ouachitensis ouachitensis), Red-eared Slider (Trachemys scripta elegans), Spotted Turtle (Clemmys guttata), Wood Turtle (Glyptemys insculpta)"
    elif state == "Wisconsin":
        return "Blandings Turtle (Emydoidea blandingii), Common Map Turtle (Graptemys geographica), Common Musk Turtle (Sternotherus odoratus), Common Snapping Turtle (Chelydra serpentina serpentina), Eastern Spiny Softshell (Apalone spinifera spinifera), False Map Turtle (Graptemys pseudogeographica pseudogeographica), Midland Painted Turtle (Chrysemys picta marginata), Midland Smooth Softshell (Apalone mutica mutica), Ornate Box Turtle (Terrapene ornata ornata), Ouachita Map Turtle Graptemys (ouachitensis ouachitensis), Western Painted Turtle (Chrysemys picta bellii), Western Spiny Softshell (Apalone spinifera hartwegi), Wood Turtle (Glyptemys insculpta)"
    elif state == "Wyoming":
        return "Common Snapping Turtle Chelydra serpentina serpentina, Ornate Box Turtle Terrapene ornata ornata, Western Painted Turtle Chrysemys picta bellii, Western Spiny Softshell Apalone spinifera hartwegi"

